version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  db-user:
    image: postgres
    container_name: postgres_user_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: userServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - db-user:/var/lib/postgresql/data
    networks:
      - kafka-network

  db-product:
    image: postgres
    container_name: postgres_product_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: productServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5434:5432"
    volumes:
      - db-product:/var/lib/postgresql/data
    networks:
      - kafka-network

  user:
    build:
      context: ./userService
    container_name: user_service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - db-user
    networks:
      - kafka-network

  auth:
    build:
      context: ./authService
    container_name: auth_service
    ports:
      - "8083:8083"
    depends_on:
      - user
    networks:
      - kafka-network

  product:
    build:
      context: ./productService
    container_name: product_service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - db-product
    networks:
      - kafka-network

volumes:
  db-user:
  db-product:

networks:
  kafka-network:
    driver: bridge
