
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  db-user:
    image: postgres:14
    container_name: postgres_user_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: userServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - db-user:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network

  db-product:
    image: postgres:14
    container_name: postgres_product_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: productServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5434:5432"
    volumes:
      - db-product:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network
  db-inventory:
    image: postgres:14 
    container_name: postgres_inventory_container
    restart: unless-stopped 
    environment:
      POSTGRES_DB: inventoryServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5435:5432"
    volumes:
      - db-inventory:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network
  db-order:
    image: postgres:14 
    container_name: postgres_order_container
    restart: unless-stopped 
    environment:
      POSTGRES_DB: orderServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5436:5432"
    volumes:
      - db-order:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kafka-network

  user:
    build:
      context: ./userService
    container_name: user_service
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_started
      db-user:
        condition: service_healthy
    networks:
      - kafka-network

  auth:
    build:
      context: ./authService
    container_name: auth_service
    ports:
      - "8083:8083"
    depends_on:
      - user
    networks:
      - kafka-network

  product:
    build:
      context: ./productService
    container_name: product_service
    ports:
      - "8084:8084"
    depends_on:
      kafka:
        condition: service_started
      db-product:
        condition: service_healthy
    networks:
      - kafka-network

  inventory:
    build:
      context: ./inventoryService
    container_name: inventory_service
    ports:
      - "8085:8085"
    depends_on:
      kafka:
        condition: service_started
      db-inventory:
        condition: service_healthy
    networks:
      - kafka-network
  order:
    build:
      context: ./orderService
    container_name: order_service
    ports:
      - "8086:8086"
    depends_on:
      kafka:
        condition: service_started
      db-order:
        condition: service_healthy
    networks:
      - kafka-network


volumes:
  db-user:
  db-product:
  db-inventory:
  db-order:

networks:
  kafka-network:
    driver: bridge
